function getRandomImage() {
    //declare an array to store the images
    var randomImage = new Array();
    
    //insert the URL of images in array
    randomImage[0] = "img/main/hacked.png";
    
    //generate a number and provide to the image to generate randomly
    var number = Math.floor(Math.random()*randomImage.length);
    
    //return the images generated by a random number
    return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';
    }

function randomImage() {
    var image = new Array(im)
    var randomNum
}